#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("input_1", 4704, hls_in, 0, "ap_vld", "in_data", 1),
	Port_Property("layer6_out_0", 6, hls_out, 1, "ap_vld", "out_data", 1),
	Port_Property("layer6_out_1", 6, hls_out, 2, "ap_vld", "out_data", 1),
	Port_Property("layer6_out_2", 6, hls_out, 3, "ap_vld", "out_data", 1),
	Port_Property("layer6_out_3", 6, hls_out, 4, "ap_vld", "out_data", 1),
	Port_Property("layer6_out_4", 6, hls_out, 5, "ap_vld", "out_data", 1),
	Port_Property("layer6_out_5", 6, hls_out, 6, "ap_vld", "out_data", 1),
	Port_Property("layer6_out_6", 6, hls_out, 7, "ap_vld", "out_data", 1),
	Port_Property("layer6_out_7", 6, hls_out, 8, "ap_vld", "out_data", 1),
	Port_Property("layer6_out_8", 6, hls_out, 9, "ap_vld", "out_data", 1),
	Port_Property("layer6_out_9", 6, hls_out, 10, "ap_vld", "out_data", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("input_1_ap_vld", 1, hls_in, 0, "ap_vld", "in_vld", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("layer6_out_0_ap_vld", 1, hls_out, 1, "ap_vld", "out_vld", 1),
	Port_Property("layer6_out_1_ap_vld", 1, hls_out, 2, "ap_vld", "out_vld", 1),
	Port_Property("layer6_out_2_ap_vld", 1, hls_out, 3, "ap_vld", "out_vld", 1),
	Port_Property("layer6_out_3_ap_vld", 1, hls_out, 4, "ap_vld", "out_vld", 1),
	Port_Property("layer6_out_4_ap_vld", 1, hls_out, 5, "ap_vld", "out_vld", 1),
	Port_Property("layer6_out_5_ap_vld", 1, hls_out, 6, "ap_vld", "out_vld", 1),
	Port_Property("layer6_out_6_ap_vld", 1, hls_out, 7, "ap_vld", "out_vld", 1),
	Port_Property("layer6_out_7_ap_vld", 1, hls_out, 8, "ap_vld", "out_vld", 1),
	Port_Property("layer6_out_8_ap_vld", 1, hls_out, 9, "ap_vld", "out_vld", 1),
	Port_Property("layer6_out_9_ap_vld", 1, hls_out, 10, "ap_vld", "out_vld", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "myproject";
